FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

LABEL DHN Chandan <php.chandan@gmail.com>

# CUDA configuration
ENV CUDA_HOME=/usr/local/cuda-11.8
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.8/lib64:/usr/local/cuda-11.8/lib64/stubs
ENV PATH=$PATH:/usr/local/cuda-11.8/bin

# Download and install Essentials
ENV GROMACS_VERSION 2022.3

RUN echo ${CUDA_HOME}
RUN echo ${LD_LIBRARY_PATH}
RUN echo ${PATH}
RUN echo ${GROMACS_VERSION}

RUN apt-get update -y &&\
    apt-get install -y build-essential curl cmake libxml2-dev python3 &&\
    curl -sL ftp://ftp.gromacs.org/pub/gromacs/gromacs-${GROMACS_VERSION}.tar.gz | tar zxfv - -C /var/tmp 

#set up installation directory
RUN mkdir /var/tmp/build

WORKDIR "/var/tmp/build"

# installing gromacs with cuda support
RUN cmake /var/tmp/gromacs-${GROMACS_VERSION} -DCMAKE_INSTALL_PREFIX=/opt/gromacs/ -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_GPU=CUDA -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.8/

